version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: online-testing-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: online_testing
      MYSQL_USER: 'testing'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3308:3306

  redis:
    image: 'redis:6-alpine'
    container_name: online-testing-redis
    ports:
      - 3009:6379
